#!/usr/bin/env python3
"""Generate the reference pages from the headers they document.

Tynima's public surfaces are two files, and both are written to be read:
sdk/include/tynima.h, the C ABI, and engine/script/lua/tynima.lua, the half
of the Lua binding written for people. Their comments are the documentation
— so the reference is not written a second time here, it is rendered:

    python3 tools/gen_docs.py            # write docs/c-api.md and docs/lua-api.md
    python3 tools/gen_docs.py --check    # exit 1 if either is out of date

What this cannot do is teach; docs/first-game.md does that, by hand. What it
can do is never be wrong, which is the failure a hand-written reference
always comes to in the end. The pages are checked in so that reading them
needs no Python, and a test regenerates them and fails when they have
drifted from the headers.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "sdk" / "include" / "tynima.h"
LUA = ROOT / "engine" / "script" / "lua" / "tynima.lua"
C_PAGE = ROOT / "docs" / "c-api.md"
LUA_PAGE = ROOT / "docs" / "lua-api.md"

BANNER = "<!-- Generated by tools/gen_docs.py from {source}. Do not edit: change\n"\
         "     the source, or run the generator. A test checks that this page still\n"\
         "     matches what it was generated from. -->"

# A comment whose first line is ---- like this ---- opens a section; one
# written with ====, a part. The header uses both, and the difference is
# where its two halves meet.
SECTION_RE = re.compile(r"^-{2,}\s*(.+?)\s*-{2,}$")
PART_RE = re.compile(r"^={2,}\s*(.+?)\s*={2,}$")
DEFINE_RE = re.compile(r"^#\s*define\s+(\w+)(?:\(([^)]*)\))?\s*(.*)$", re.S)
LUA_SECTION_RE = re.compile(r"^--\s-{3,}\s*(.*\S)\s*$")
LUA_FUNCTION_RE = re.compile(r"^function\s+(ty\.\w+)\s*\(([^)]*)\)")


# ------------------------------------------------------------------ the C header

def strip_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/", " ", text, flags=re.S)


def as_markdown(lines: list[str]) -> list[str]:
    """Lines indented inside a comment were indented for a reason — they are
    a program, or a list. Markdown reads four spaces as a block of code, so
    each run of them is given exactly that, keeping what is nested inside."""
    out: list[str] = []
    i = 0
    while i < len(lines):
        if not lines[i].startswith(" "):
            out.append(lines[i])
            i += 1
            continue
        run: list[str] = []
        j = i
        while j < len(lines) and (lines[j].startswith(" ") or not lines[j].strip()):
            run.append(lines[j])
            j += 1
        while run and not run[-1].strip():
            run.pop()
            j -= 1
        base = min(len(l) - len(l.lstrip()) for l in run if l.strip())
        out.append("")
        out.extend("    " + l[base:] if l.strip() else "" for l in run)
        out.append("")
        i = j
    return out


def comment_text(block: str) -> str:
    """A /* block */ as the prose inside it, one line to a line."""
    inner = block[2:-2] if block.endswith("*/") else block[2:]
    raw = inner.splitlines()
    # /* ate the indentation of whatever was written on its own line.
    opens_with_text = bool(raw and raw[0].strip())
    lines = []
    for line in raw:
        stripped = line.lstrip()
        lines.append((stripped[1:] if stripped.startswith("*") else line).rstrip())
    head = [lines[0].strip()] if opens_with_text else []
    body = lines[1:] if opens_with_text else lines
    indents = [len(l) - len(l.lstrip()) for l in body if l.strip()]
    cut = min(indents) if indents else 0
    lines = head + [line[cut:] if line.strip() else "" for line in body]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(as_markdown(lines)).strip()


def chunks(text: str) -> list[tuple[str, str, int, int]]:
    """C as a list of (kind, text): comment, define, other preprocessor, declaration.

    The scanner is the one gen_lua.py uses — a statement ends at the
    semicolon outside any brace, a `static inline` definition at its closing
    brace — with the comments kept rather than thrown away, since here they
    are the point.
    """
    out: list[tuple[str, str, int, int]] = []
    i, length = 0, len(text)
    while i < length:
        char = text[i]
        if char.isspace():
            i += 1
            continue
        if text.startswith("/*", i):
            end = text.find("*/", i)
            end = length if end < 0 else end + 2
            out.append(("comment", text[i:end], i, end))
            i = end
            continue
        if char == "#":
            end = text.find("\n", i)
            end = length if end < 0 else end
            while text[i:end].rstrip().endswith("\\"):
                nxt = text.find("\n", end + 1)
                end = length if nxt < 0 else nxt
            out.append(("pp", text[i:end], i, end))
            i = end + 1
            continue
        # The extern "C" wrapper and the brace that closes it are not
        # declarations of anything.
        if text.startswith("extern", i) or char == "}":
            end = text.find("\n", i)
            i = length if end < 0 else end + 1
            continue
        start = i
        definition = text.startswith("static inline", i)
        depth, opened = 0, False
        while i < length:
            if text.startswith("/*", i):
                end = text.find("*/", i)
                i = length if end < 0 else end + 2
                continue
            char = text[i]
            if char == "{":
                depth += 1
                opened = True
            elif char == "}":
                depth -= 1
                if definition and opened and depth == 0:
                    i += 1
                    break
            elif char == ";" and depth == 0:
                break
            i += 1
        out.append(("decl", text[start:i].strip(), start, i))
        i += 1
    return out


def declared_name(decl: str) -> str:
    """What a declaration declares: the typedef's name, or the function's."""
    text = " ".join(strip_comments(decl).split())
    # A function pointer wears its name in the middle: (*name)(args). Only
    # where there is no body, or the first member of a table of them would
    # answer for the table.
    pointer = re.search(r"\(\s*\*\s*([A-Za-z_]\w*)\s*\)", text) if "{" not in text else None
    if pointer is not None:
        return pointer.group(1)
    if text.startswith("typedef"):
        names = re.findall(r"[A-Za-z_]\w*", text)
        return names[-1] if names else text
    head = text.split("(", 1)[0]
    names = re.findall(r"[A-Za-z_]\w*", head)
    return names[-1] if names else text


def code(text: str) -> str:
    """A declaration as C. An inline definition ends at its brace and wants
    no semicolon; everything else is a declaration and wants exactly one."""
    body = text.rstrip()
    if not body.endswith("}"):
        body = body.rstrip(";") + ";"
    return "```c\n" + body + "\n```"


def slug(heading: str) -> str:
    """The anchor a Markdown renderer gives a heading: its own rule — fold to
    lower case, drop everything that is not a letter, digit, underscore,
    space or dash, and turn runs of space into one dash."""
    text = re.sub(r"[^\w\s-]", "", heading.strip().lower())
    return re.sub(r"\s+", "-", text)


def api_table(decl: str) -> list[str]:
    """The entries of tynima_api, one heading each: the reference a game reads.

    The table is a hundred and fifty lines of function pointers, each with
    the comment that says what it does. As one block it is unreadable; as
    one heading per entry it is the index of everything a game can call.
    """
    body = decl[decl.index("{") + 1:decl.rindex("}")]
    out: list[str] = []
    pending: list[str] = []
    last_end: int | None = None
    for kind, text, start, end in chunks(body):
        if kind == "comment":
            prose = comment_text(text)
            first = prose.splitlines()[0] if prose else ""
            match = SECTION_RE.match(first.strip())
            if match:
                rest = "\n".join(prose.splitlines()[1:]).strip()
                out.append(f"#### {match.group(1)}\n")
                if rest:
                    out.append(rest + "\n")
                pending, last_end = [], None
                continue
            # A note on the same line as the declaration before it is that
            # declaration's, not the next one's.
            if last_end is not None and "\n" not in body[last_end:start] and out:
                out.insert(len(out) - 1, prose + "\n")
                last_end = end
                continue
            pending.append(prose)
            continue
        if kind != "decl" or not text.strip():
            continue
        name = declared_name(text)
        out.append(f"##### `{name}`\n")
        if pending:
            out.append("\n\n".join(p for p in pending if p) + "\n")
        # The member was indented inside the table; its continuation lines
        # still are, and here there is nothing for them to line up with.
        out.append(code(re.sub(r"\n {4}", "\n", text)) + "\n")
        pending, last_end = [], end
    return out


def c_page() -> str:
    text = HEADER.read_text(encoding="utf-8")
    items = chunks(text)
    out: list[str] = []
    index: list[tuple[str, str]] = []  # section, name
    section = "Overview"
    pending: list[str] = []
    intro_taken = False
    constants: list[tuple[str, str, str]] = []

    last_end: int | None = None
    for kind, raw, start, end in items:
        if kind == "comment":
            prose = comment_text(raw)
            first = prose.splitlines()[0].strip() if prose else ""
            part = PART_RE.match(first)
            sect = SECTION_RE.match(first)
            if part or sect:
                section = (part or sect).group(1)
                rest = "\n".join(prose.splitlines()[1:]).strip()
                out.append(f"\n## {section}\n")
                if rest:
                    out.append(rest + "\n")
                pending, last_end = [], None
                continue
            if not intro_taken:
                intro_taken = True
                out.append(prose + "\n")
                continue
            if last_end is not None and "\n" not in text[last_end:start] and out:
                out.insert(len(out) - 1, prose + "\n")  # a note at the end of its line
                last_end = end
                continue
            pending.append(prose)
            continue

        if kind == "pp":
            match = DEFINE_RE.match(" ".join(raw.split()))
            if match is None or match.group(2) is not None:
                continue
            name, value = match.group(1), match.group(3).strip()
            # A trailing comment on the line is the constant's own note.
            trailing = re.search(r"/\*(.*?)\*/", value)
            value = strip_comments(value).strip()
            # Only a value is a constant worth looking up: a macro that
            # expands to an attribute is the compiler's business, and it is
            # spelled differently on every platform anyway.
            if name == "TYNIMA_H" or not re.fullmatch(r'(0[xX][0-9a-fA-F]+|\d+)[uUlL]*|".*"', value):
                pending = []
                continue
            note = trailing.group(1).strip() if trailing else ""
            # A one-line comment above a #define describes it; a paragraph
            # describes whatever is declared under it, so leave that alone.
            if not note and len(pending) == 1 and "\n" not in pending[0]:
                note = pending[0]
                pending = []
            constants.append((name, value, note))
            continue

        if kind != "decl" or not raw.strip():
            continue
        name = declared_name(raw)
        index.append((section, name))
        out.append(f"### `{name}`\n")
        if pending:
            out.append("\n\n".join(p for p in pending if p) + "\n")
        if name == "tynima_api":
            out.append(code(f"typedef struct {name} {{ ... }} {name}") + "\n")
            out.extend(api_table(raw))
        else:
            out.append(code(raw) + "\n")
        pending, last_end = [], end

    head = [
        BANNER.format(source="sdk/include/tynima.h"),
        "",
        "# The C API",
        "",
        "`sdk/include/tynima.h` is the whole of what a game may call, and a game",
        "needs no other file from this repository. What follows is that header,",
        "rendered: its prose, and the declaration each piece of it describes.",
        "",
    ]
    if constants:
        head.append("## Constants\n")
        head.append("| name | value | |")
        head.append("| --- | --- | --- |")
        for name, value, note in constants:
            summary = " ".join(note.split())
            head.append(f"| `{name}` | `{value}` | {summary} |")
        head.append("")
    head.append("## Index\n")
    sections: dict[str, list[str]] = {}
    for sect, name in index:
        sections.setdefault(sect, []).append(name)
    for sect, names in sections.items():
        links = ", ".join(f"[`{name}`](#{slug(name)})" for name in names)
        head.append(f"**{sect}** — {links}\n")
    return "\n".join(head) + "\n" + "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------- the Lua

def lua_page() -> str:
    lines = LUA.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    index: list[tuple[str, str]] = []
    doc: list[str] = []
    intro: list[str] = []
    i = 0
    # The file opens with its own comment: that is the page's introduction.
    while i < len(lines) and lines[i].startswith("--"):
        # Only the comment marker and one space come off: what is indented
        # inside the comment is a program, and Markdown reads four spaces
        # as one.
        line = lines[i][2:]
        intro.append(line[1:] if line.startswith(" ") else line)
        i += 1
    while i < len(lines):
        line = lines[i]
        section = LUA_SECTION_RE.match(line)
        if section is not None:
            out.append(f"\n## {section.group(1)}\n")
            doc = []
            i += 1
            continue
        if line.startswith("--- "):
            doc.append(line[4:].rstrip())
            i += 1
            continue
        if line.strip() == "---":
            doc.append("")
            i += 1
            continue
        function = LUA_FUNCTION_RE.match(line)
        if function is not None:
            name, args = function.group(1), " ".join(function.group(2).split())
            heading = f"{name}({args})"
            index.append((name, slug(heading)))
            out.append(f"### `{heading}`\n")
            if doc:
                out.append("\n".join(doc).strip() + "\n")
            doc = []
            i += 1
            continue
        if line.strip():
            doc = []
        i += 1

    head = [
        BANNER.format(source="engine/script/lua/tynima.lua"),
        "",
        "# The Lua API",
        "",
        "\n".join(intro).strip(),
        "",
        "## Index\n",
        ", ".join(f"[`{name}`](#{anchor})" for name, anchor in index),
        "",
    ]
    return "\n".join(head) + "\n" + "\n".join(out).strip() + "\n"


# -------------------------------------------------------------------- the tool

PAGES = ((C_PAGE, c_page), (LUA_PAGE, lua_page))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="only report whether the pages are current")
    args = parser.parse_args()

    stale = False
    for path, build in PAGES:
        generated = build()
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current == generated:
                print(f"{path.relative_to(ROOT)} is up to date")
                continue
            print(f"{path.relative_to(ROOT)} is out of date: run tools/gen_docs.py", file=sys.stderr)
            stale = True
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
