#!/usr/bin/env python3
"""Regenerates engine/platform/include/tynima/platform/keys.def from KEYS.

Add a key to KEYS (append, to keep enum values stable), run this, rebuild.
"""
from pathlib import Path

KEYS = [('Unknown', 'SDL_SCANCODE_UNKNOWN'), ('A', 'SDL_SCANCODE_A'), ('B', 'SDL_SCANCODE_B'), ('C', 'SDL_SCANCODE_C'), ('D', 'SDL_SCANCODE_D'), ('E', 'SDL_SCANCODE_E'), ('F', 'SDL_SCANCODE_F'), ('G', 'SDL_SCANCODE_G'), ('H', 'SDL_SCANCODE_H'), ('I', 'SDL_SCANCODE_I'), ('J', 'SDL_SCANCODE_J'), ('K', 'SDL_SCANCODE_K'), ('L', 'SDL_SCANCODE_L'), ('M', 'SDL_SCANCODE_M'), ('N', 'SDL_SCANCODE_N'), ('O', 'SDL_SCANCODE_O'), ('P', 'SDL_SCANCODE_P'), ('Q', 'SDL_SCANCODE_Q'), ('R', 'SDL_SCANCODE_R'), ('S', 'SDL_SCANCODE_S'), ('T', 'SDL_SCANCODE_T'), ('U', 'SDL_SCANCODE_U'), ('V', 'SDL_SCANCODE_V'), ('W', 'SDL_SCANCODE_W'), ('X', 'SDL_SCANCODE_X'), ('Y', 'SDL_SCANCODE_Y'), ('Z', 'SDL_SCANCODE_Z'), ('Digit0', 'SDL_SCANCODE_0'), ('Digit1', 'SDL_SCANCODE_1'), ('Digit2', 'SDL_SCANCODE_2'), ('Digit3', 'SDL_SCANCODE_3'), ('Digit4', 'SDL_SCANCODE_4'), ('Digit5', 'SDL_SCANCODE_5'), ('Digit6', 'SDL_SCANCODE_6'), ('Digit7', 'SDL_SCANCODE_7'), ('Digit8', 'SDL_SCANCODE_8'), ('Digit9', 'SDL_SCANCODE_9'), ('F1', 'SDL_SCANCODE_F1'), ('F2', 'SDL_SCANCODE_F2'), ('F3', 'SDL_SCANCODE_F3'), ('F4', 'SDL_SCANCODE_F4'), ('F5', 'SDL_SCANCODE_F5'), ('F6', 'SDL_SCANCODE_F6'), ('F7', 'SDL_SCANCODE_F7'), ('F8', 'SDL_SCANCODE_F8'), ('F9', 'SDL_SCANCODE_F9'), ('F10', 'SDL_SCANCODE_F10'), ('F11', 'SDL_SCANCODE_F11'), ('F12', 'SDL_SCANCODE_F12'), ('Escape', 'SDL_SCANCODE_ESCAPE'), ('Enter', 'SDL_SCANCODE_RETURN'), ('Tab', 'SDL_SCANCODE_TAB'), ('Backspace', 'SDL_SCANCODE_BACKSPACE'), ('Space', 'SDL_SCANCODE_SPACE'), ('Minus', 'SDL_SCANCODE_MINUS'), ('Equals', 'SDL_SCANCODE_EQUALS'), ('LeftBracket', 'SDL_SCANCODE_LEFTBRACKET'), ('RightBracket', 'SDL_SCANCODE_RIGHTBRACKET'), ('Backslash', 'SDL_SCANCODE_BACKSLASH'), ('Semicolon', 'SDL_SCANCODE_SEMICOLON'), ('Apostrophe', 'SDL_SCANCODE_APOSTROPHE'), ('Grave', 'SDL_SCANCODE_GRAVE'), ('Comma', 'SDL_SCANCODE_COMMA'), ('Period', 'SDL_SCANCODE_PERIOD'), ('Slash', 'SDL_SCANCODE_SLASH'), ('CapsLock', 'SDL_SCANCODE_CAPSLOCK'), ('Insert', 'SDL_SCANCODE_INSERT'), ('Delete', 'SDL_SCANCODE_DELETE'), ('Home', 'SDL_SCANCODE_HOME'), ('End', 'SDL_SCANCODE_END'), ('PageUp', 'SDL_SCANCODE_PAGEUP'), ('PageDown', 'SDL_SCANCODE_PAGEDOWN'), ('Left', 'SDL_SCANCODE_LEFT'), ('Right', 'SDL_SCANCODE_RIGHT'), ('Up', 'SDL_SCANCODE_UP'), ('Down', 'SDL_SCANCODE_DOWN'), ('LeftShift', 'SDL_SCANCODE_LSHIFT'), ('RightShift', 'SDL_SCANCODE_RSHIFT'), ('LeftCtrl', 'SDL_SCANCODE_LCTRL'), ('RightCtrl', 'SDL_SCANCODE_RCTRL'), ('LeftAlt', 'SDL_SCANCODE_LALT'), ('RightAlt', 'SDL_SCANCODE_RALT'), ('LeftSuper', 'SDL_SCANCODE_LGUI'), ('RightSuper', 'SDL_SCANCODE_RGUI')]

def main() -> None:
    lines = ["// Generated by tools/gen_keys.py (see also engine/platform/src/input.cpp).",
             "// Every consumer defines TYNIMA_KEY(name, sdl_scancode) then includes this.",
             "// The order is the enum order; append new keys at the end to keep values stable."]
    lines += [f"TYNIMA_KEY({name}, {scancode})" for name, scancode in KEYS]
    out = Path(__file__).resolve().parent.parent / "engine/platform/include/tynima/platform/keys.def"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(KEYS)} keys)")

if __name__ == "__main__":
    main()
